added/scrollbar
anand-harsh/Edumi pull request #59
Opened 2024-01-16 06:48 UTC by itsmeabhishek03

*Have you read the [Contributing Guidelines](https://github.com/jessesquires/.github/blob/master/CONTRIBUTING.md)?* 
Yes

Issue #47

## Describe your changes
I made a small change in style.css file in client directory. Now it looks like this - 
![image](https://github.com/anand-harsh/Edumi/assets/104294494/74e417f9-dbf9-4c8d-821f-938b1f66e97d)

![image](https://github.com/anand-harsh/Edumi/assets/104294494/b0031eaf-5803-4814-be97-ce3567b8e8b5)

2024-01-16 06:51 UTC, anand-harsh commented
Hi @itsmeabhishek03 , Kindly change the color of scrollbar to yellow in light mode and white in dark mode

2024-01-16 07:02 UTC, anand-harsh requested changes
Do the changes told for the colors

2024-01-16 07:23 UTC, itsmeabhishek03 commented
> Hi @itsmeabhishek03 , Kindly change the color of scrollbar to yellow in light mode and white in dark mode

ok

2024-01-16 12:36 UTC, anand-harsh commented
@itsmeabhishek03 , RESOLVE THE ISSUE ASAP, its already up the deadline, if you are late, points wont get counted

2024-01-17 05:46 UTC, anand-harsh commented
Hi @itsmeabhishek03 any updates?

2024-01-17 14:04 UTC, anand-harsh commented
Hi @itsmeabhishek03 , your deadline is over, either you finish it by tonight, or this will be merged and you won't get the points

2024-01-18 02:09 UTC, anand-harsh requested changes
Do the changes

2024-01-18 02:09 UTC, anand-harsh commented on client/src/style.css
> +    background: linear-gradient(to top, #f57811 , #1d08ba);
add yellow background here for scrollbar

2024-01-18 12:37 UTC, closed without merging