Adding Route for User Role Updation
anand-harsh/Edumi pull request #63
Opened 2024-01-16 15:28 UTC by JavidSumra

*Have you read the [Contributing Guidelines](https://github.com/jessesquires/.github/blob/master/CONTRIBUTING.md)?*  Yes

Issue #45 

## Describe your changes
With POST request to /api/admin/user/:id will attempt to update the user's role to "admin," provided the user exists and currently has the role of "user." The route handles different scenarios, such as user not found, user already being an admin, or any other errors during the process.

![image](https://github.com/anand-harsh/Edumi/assets/112365664/7b36394e-8ea7-464e-9746-e25e880191e1)

2024-01-16 15:56 UTC, anand-harsh requested changes
Hi @JavidSumra , don't commit package-lock.json and package.json, just use

git add <file.js> instead of git add .

2024-01-16 16:43 UTC, JavidSumra commented
Hey @anand-harsh I made Changes by Unstaging `package.json` and `package-lock.json` now you can Check API.

2024-01-16 16:46 UTC, anand-harsh commented
> Hey @anand-harsh I made Changes by Unstaging `package.json` and `package-lock.json` now you can Check API.

Yes, check the other things need to be resolved, I have mentioned above

2024-01-16 17:02 UTC, anand-harsh commented
hI @JavidSumra , ONCE UPDATE YOUR BRANCH

2024-01-17 05:41 UTC, anand-harsh requested changes
Update your branch to latest commit to resolve conflicts

2024-01-17 05:55 UTC, JavidSumra commented on routes/userRoutes.js
> +router.route("/admin/user/:id").post(isAuthenticated, updateUserRole);
Hey I will do it by tonight.

2024-01-17 13:11 UTC, JavidSumra commented
Hey @anand-harsh Please Checkout Now my PR.

2024-01-17 13:51 UTC, JavidSumra commented
Hey @anand-harsh Shall I need to Create a New Branch?

2024-01-17 13:56 UTC, merged

2024-01-17 13:57 UTC, anand-harsh commented
LGTM✨✨