Added a feature to add courses to playlist of the user
anand-harsh/Edumi pull request #80
Opened 2024-01-21 05:20 UTC by Divyanshgarg-04

Added a feature to add courses to playlist of the user

2024-01-21 17:09 UTC, Divyanshgarg-04 commented
@anand-harsh Kindly check the changes and if any other changes are required please let me know

2024-01-22 06:24 UTC, anand-harsh commented
Share me screenshot of the response and url you using, means full screenshot of postman

2024-01-22 06:50 UTC, Divyanshgarg-04 commented
courses present
<img width="856" alt="image" src="https://github.com/anand-harsh/Edumi/assets/120127517/6a1a3afc-603c-44e2-8656-acc77f625289">

Course already in the playlist
<img width="858" alt="image" src="https://github.com/anand-harsh/Edumi/assets/120127517/5313bae7-53e7-4248-b78c-24ed29af6b1e">


For new course
<img width="845" alt="image" src="https://github.com/anand-harsh/Edumi/assets/120127517/0f2d97a0-1251-4a92-9664-faf7df3368f8">

Adding the new course to playlist
<img width="852" alt="image" src="https://github.com/anand-harsh/Edumi/assets/120127517/c6d7c799-d87f-4ba2-87c0-050167b92303">

2024-01-22 15:11 UTC, Divyanshgarg-04 commented
@anand-harsh  any suggestions?

2024-01-23 04:54 UTC, anand-harsh requested changes
Also update your branch and all good to go

2024-01-23 04:54 UTC, anand-harsh commented on controllers/userController.js
> +export const addCourse = catchAsyncError (async(req, res, next) => {
rename component to "addCourseToUserPlaylist"

2024-01-23 05:31 UTC, closed without merging