Adding Feature of Authentication
anand-harsh/Edumi pull request #82
Opened 2024-01-21 16:01 UTC by JavidSumra

[x] *Have you read the [Contributing Guidelines](https://github.com/jessesquires/.github/blob/master/CONTRIBUTING.md)?*

Issue #37 

## Describe your changes
Introducing seamless features for user login, signup, and logout. This enhancement enhances the project's user experience by providing secure and user-friendly authentication functionalities.

2024-01-21 16:09 UTC, anand-harsh requested changes
If user is not logged in then he cant access anything in application, just show Login and signup button on page, and after successful login, redirect to main application. Hope you get that. Also for knowing whether user is logged in or not, change name on view profile by name of user or email of user

2024-01-21 16:12 UTC, JavidSumra commented
Hey @anand-harsh I will do it by tomorrow and yes you need to add an environment variable named `REACT_APP_API_ENDPOINT` with the value of the backend url in production.

2024-01-22 10:57 UTC, JavidSumra commented
Hey @anand-harsh Sir Can You Please Add `Labels` over here?

2024-01-22 16:27 UTC, anand-harsh commented
Hi, the auth part is not working for me in my local, can you guide me what things I need to do to?, like env

2024-01-23 01:58 UTC, JavidSumra commented
Hey @anand-harsh  you need to add an environment variable named `REACT_APP_API_ENDPOINT` with the value of the backend url in production.

2024-01-23 04:44 UTC, anand-harsh requested changes
The content of other pages are not visible after login, fix it

2024-01-23 04:44 UTC, anand-harsh commented on client/src/components/Auth/Register.jsx
> +        body: JSON.stringify({ email, name, password, image }),
Don't take image for now, just take name, email, password

2024-01-23 05:00 UTC, JavidSumra commented
> The content of other pages are not visible after login, fix it

Hey @anand-harsh Can You Please Share Screenshot with Console?

2024-01-23 10:43 UTC, anand-harsh requested changes
Do changes and let me know

2024-01-23 10:43 UTC, anand-harsh commented on client/src/components/Auth/Login.jsx
> +          JSON.stringify({ User: data?.user }),
Just add email and createdAt feild in localStorage, dont add whole data

2024-01-23 10:46 UTC, JavidSumra commented
Hey @anand-harsh From the Backend I am Just Getting Data Like Name,email and createdAt for Login

2024-01-23 10:47 UTC, anand-harsh commented
> Hey @anand-harsh From the Backend I am Just Getting Data Like Name,email and createdAt for Login

No issues, just dont add all data to localStorage, as its vulnerable

2024-01-23 10:56 UTC, JavidSumra commented
Hey @anand-harsh Changes Done!!!

2024-01-23 13:36 UTC, anand-harsh commented
Hi @JavidSumra , the pages are still not visible, come to discord

2024-01-24 13:33 UTC, anand-harsh approved these changes
LGTM✨✨

2024-01-24 13:33 UTC, merged